import { useEffect, useMemo, useState } from "react";
import {
  Badge,
  Box,
  Button,
  Card,
  Flex,
  FormControl,
  Heading,
  Note,
  Paragraph,
  Spinner,
  Table,
  TextInput,
  Textarea,
} from "@contentful/f36-components";
import type { PageExtensionSDK } from "@contentful/app-sdk";
import { useSDK } from "@contentful/react-apps-toolkit";

import { bootstrapBuilder, createProject, getProjectDetail, startRun, subscribeToRun } from "../api.js";
import type {
  BuilderInstallationParameters,
  BuilderProject,
  BuilderProjectDetail,
} from "../types.js";

function getInstallationParameters(sdk: PageExtensionSDK): BuilderInstallationParameters {
  const params = (sdk.parameters.installation ?? {}) as Partial<BuilderInstallationParameters>;
  return {
    tenantId: params.tenantId ?? "internal-demo",
    githubInstallationId: params.githubInstallationId ?? "",
    openAiSecretRef: params.openAiSecretRef ?? "",
    previewTarget: params.previewTarget ?? "contentful-preview",
    productionTarget: params.productionTarget ?? "contentful-production",
    policyProfileId: params.policyProfileId ?? "default",
    apiBaseUrl: params.apiBaseUrl ?? import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8787",
    featureFlags: params.featureFlags ?? {},
  };
}

export function Page() {
  const sdk = useSDK<PageExtensionSDK>();
  const installation = useMemo(() => getInstallationParameters(sdk), [sdk]);
  const [projects, setProjects] = useState<BuilderProject[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState<string>("");
  const [projectDetail, setProjectDetail] = useState<BuilderProjectDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [projectName, setProjectName] = useState("Managed app demo");
  const [projectDescription, setProjectDescription] = useState("Generated by the Codex-powered builder.");
  const [prompt, setPrompt] = useState("Create a sidebar experience that summarizes entry metadata and surfaces a preview call-to-action.");
  const [runLog, setRunLog] = useState<string[]>([]);
  const [activeRunId, setActiveRunId] = useState<string>("");

  useEffect(() => {
    let isMounted = true;
    setIsLoading(true);
    bootstrapBuilder(installation)
      .then((response) => {
        if (!isMounted) {
          return;
        }
        setProjects(response.projects);
        setSelectedProjectId((current) => current || response.projects[0]?.id || "");
      })
      .catch((error: Error) => sdk.notifier.error(error.message))
      .finally(() => {
        if (isMounted) {
          setIsLoading(false);
        }
      });

    return () => {
      isMounted = false;
    };
  }, [installation, sdk]);

  useEffect(() => {
    if (!selectedProjectId) {
      setProjectDetail(null);
      return;
    }

    getProjectDetail(installation, selectedProjectId)
      .then(setProjectDetail)
      .catch((error: Error) => sdk.notifier.error(error.message));
  }, [installation, sdk, selectedProjectId]);

  useEffect(() => {
    if (!activeRunId) {
      return;
    }

    const unsubscribe = subscribeToRun(installation, activeRunId, (event) => {
      setRunLog((current) => [...current, JSON.stringify(event)]);
      void getProjectDetail(installation, selectedProjectId)
        .then(setProjectDetail)
        .catch(() => undefined);
    });

    return unsubscribe;
  }, [activeRunId, installation, selectedProjectId]);

  async function handleCreateProject() {
    const project = await createProject(installation, {
      tenantId: installation.tenantId,
      name: projectName,
      description: projectDescription,
      supportedSurfaces: ["ConfigScreen", "Page", "Sidebar"],
    });

    setProjects((current) => [project as BuilderProject, ...current]);
    setSelectedProjectId((project as BuilderProject).id);
    sdk.notifier.success("Managed project scaffold created.");
  }

  async function handleStartRun() {
    if (!selectedProjectId) {
      sdk.notifier.error("Create or select a project first.");
      return;
    }

    setRunLog([]);
    const response = await startRun(installation, selectedProjectId, prompt);
    setActiveRunId(response.runId);
    sdk.notifier.success("Codex run started.");
  }

  return (
    <Flex flexDirection="column" gap="spacingL">
      <Box
        padding="spacingL"
        style={{
          borderRadius: 18,
          background: "linear-gradient(135deg, #102542 0%, #1d3557 55%, #457b9d 100%)",
          color: "white",
        }}
      >
        <Heading>Codex Builder Workspace</Heading>
        <Paragraph>
          Build managed Contentful apps from inside Contentful while keeping Codex execution on the server.
        </Paragraph>
        <Flex gap="spacingS" alignItems="center">
          <Badge variant="primary">{installation.tenantId}</Badge>
          <Badge variant="secondary">{installation.previewTarget}</Badge>
          <Badge variant="positive">{installation.productionTarget}</Badge>
        </Flex>
      </Box>

      <Note variant="warning">
        Stage 1 uses a Render-compatible demo backend. Expect cold starts and keep this limited to internal or tightly managed use.
      </Note>

      <Card>
        <Flex flexDirection="column" gap="spacingM">
          <Heading>Create a managed project</Heading>
          <FormControl>
            <FormControl.Label>Project name</FormControl.Label>
            <TextInput value={projectName} onChange={(event) => setProjectName(event.target.value)} />
          </FormControl>
          <FormControl>
            <FormControl.Label>Description</FormControl.Label>
            <Textarea value={projectDescription} onChange={(event) => setProjectDescription(event.target.value)} />
          </FormControl>
          <Button variant="primary" onClick={() => void handleCreateProject()}>
            Create managed project
          </Button>
        </Flex>
      </Card>

      <Card>
        <Flex flexDirection="column" gap="spacingM">
          <Heading>Projects</Heading>
          {isLoading ? <Spinner /> : null}
          {projects.length === 0 && !isLoading ? <Paragraph>No projects yet.</Paragraph> : null}
          {projects.map((project) => (
            <Box
              key={project.id}
              padding="spacingM"
              style={{
                borderRadius: 12,
                border: project.id === selectedProjectId ? "2px solid #0f62fe" : "1px solid #dce3ec",
                cursor: "pointer",
              }}
              onClick={() => setSelectedProjectId(project.id)}
            >
              <Flex justifyContent="space-between" alignItems="center">
                <div>
                  <Heading marginBottom="none">{project.name}</Heading>
                  <Paragraph marginBottom="none">{project.description}</Paragraph>
                </div>
                <Badge variant="secondary">{project.manifest.supportedSurfaces.join(", ")}</Badge>
              </Flex>
            </Box>
          ))}
        </Flex>
      </Card>

      <Card>
        <Flex flexDirection="column" gap="spacingM">
          <Heading>Run Codex</Heading>
          <FormControl>
            <FormControl.Label>Prompt</FormControl.Label>
            <Textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={6} />
          </FormControl>
          <Button variant="primary" onClick={() => void handleStartRun()}>
            Start run
          </Button>
        </Flex>
      </Card>

      {projectDetail ? (
        <Card>
          <Flex flexDirection="column" gap="spacingM">
            <Heading>Project detail</Heading>
            <Paragraph>
              Workspace: <code>{projectDetail.project.workspacePath}</code>
            </Paragraph>
            <Table>
              <Table.Head>
                <Table.Row>
                  <Table.Cell>Status</Table.Cell>
                  <Table.Cell>Prompt</Table.Cell>
                  <Table.Cell>Updated</Table.Cell>
                </Table.Row>
              </Table.Head>
              <Table.Body>
                {projectDetail.runs.map((run) => (
                  <Table.Row key={run.id}>
                    <Table.Cell>
                      <Badge variant={run.status === "succeeded" ? "positive" : run.status === "failed" ? "negative" : "primary"}>
                        {run.status}
                      </Badge>
                    </Table.Cell>
                    <Table.Cell>{run.prompt}</Table.Cell>
                    <Table.Cell>{new Date(run.updatedAt).toLocaleString()}</Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table>
          </Flex>
        </Card>
      ) : null}

      <Card>
        <Flex flexDirection="column" gap="spacingM">
          <Heading>Live run stream</Heading>
          <Box
            padding="spacingM"
            style={{
              borderRadius: 12,
              background: "#0f172a",
              color: "#dbeafe",
              fontFamily: "monospace",
              minHeight: 220,
              whiteSpace: "pre-wrap",
              overflowX: "auto",
            }}
          >
            {runLog.length > 0 ? runLog.join("\n") : "No run output yet."}
          </Box>
        </Flex>
      </Card>
    </Flex>
  );
}
